### PR TITLE
Add support for other intervals

### PR DESCRIPTION
**Pull request by tito10047**
Add support for day/hour/month interval instead of harcoded day

### CODE REVIEW

**Comment by tito10047** [comment]
Hi, will you be reviewing this pull request anytime soon? I'm just wondering if I should publish my own package or wait for the request to be accepted.

Thanks

**Comment by brendt** [comment]
I lost track of this one, sorry! Let me get back to it next week, does that work for you?

**Comment by tito10047** [comment]
No problem at all! Take your time.
Thanks

**Comment by brendt** [comment]
Ok, I managed to take a look at it! So, in hindsight, I think this package should have been unaware of the time period, making this problem go away in full. It should just render a collection of points, regardless of the meaning of the y-axis (because the y-axis is never visually shown anyway, that's the nature of a sparkline).

I actually planned on making a new major version of this package with that change, but I never came to it. I might in the future though, especially if I know people are still using it. 

So, I don't think I wanna take the approach of this PR, but I agree it should be improved. I'll try to look at it this week :)

**Comment by brendt** [comment]
I've tagged v2, which is totally agnostic about periods: https://github.com/brendt/php-sparkline/releases/tag/2.0.0

**Pull request closed without merging**
